config/routes.rb
HeadShot::Application.routes.draw do
  resources :shots
  resources :users

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'

  root :to => 'pages#home'

end

app/models/shot.rb
# == Schema Information
#
# Table name: shots
#
#  id         :integer         not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  push_url   :string(255)
#

class Shot < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  data       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

end

app/controllers/shots_controller.rb
dir = File.expand_path(File.join(File.dirname(__FILE__), '../../', 'lib'))
require File.join(dir, 'Push')

class ShotsController < ApplicationController
  include HTTParty
  
  # GET /shots
  # GET /shots.xml
  def index
    @shots = Shot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shots }
    end
  end

  # GET /shots/1
  # GET /shots/1.xml
  def show
    @shot = Shot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shot }
    end
  end

  # GET /shots/new
  # GET /shots/new.xml
  def new
    @shot = Shot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shot }
    end
  end

  # GET /shots/1/edit
  def edit
    @shot = Shot.find(params[:id])
  end

  # POST /shots
  # POST /shots.xml
  def create
    @shot = Shot.new(params[:shot])
    
    send_notification_to_phone(@shot)
    
    respond_to do |format|
      if @shot.save
        format.html { redirect_to(@shot, :notice => 'Shot was successfully created.') }
        format.xml  { render :xml => @shot, :status => :created, :location => @shot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shots/1
  # PUT /shots/1.xml
  def update
    @shot = Shot.find(params[:id])

    respond_to do |format|
      if @shot.update_attributes(params[:shot])
        format.html { redirect_to(@shot, :notice => 'Shot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.xml
  def destroy
    @shot = Shot.find(params[:id])
    @shot.destroy

    respond_to do |format|
      format.html { redirect_to(shots_url) }
      format.xml  { head :ok }
    end
  end
  
  private 
    def send_notification_to_phone(shot)
       url = shot.push_url
       return if url.nil?
       message = 'hola!'     
       options = { :body => message, :headers => {'X-NotificationClass' => '3'} }
       Push.post(url, options)
       return
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Head Shot Augmented Reality Phone Game"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("SplashScreenImage.jpg", :size => '180x80', :alt => "Sample App", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", '/' %></li>
      <li><%= link_to "Sign in", '/' %></li>
      <li><%= link_to "About", '/about' %></li>
		<li><%= link_to "Contact", '/contact' %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
	<%= javascript_include_tag :defaults %>
	<%= render	'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
	  <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  Windows Phone owners, on the same Wifi network, can play the classic tag game. Start the game to see the cross-hairs. Center the cross-hairs and click the shutter button for the kill. Your opponent will receive a notification that they've been tagged.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Head Shot Augmented Reality Phone Game team at <a href="mailto:perry.zheng@gmail.com?Subject=Head Shot">perry.zheng@gmail.com</a> or <a href="mailto:lewislin@gmail.com?Subject=Head Shot">lewislin@gmail.com</a>.
</p>

app/views/pages/home.html.erb
<h1>Head Shot Augmented Reality Phone Game</h1>
<p>
  This is the home page for the
  <a href="/">Head Shot Augmented Reality Phone Game</a>
  sample application.
</p>

<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

app/views/shots/_form.html.erb
<%= form_for(@shot) do |f| %>
  <% if @shot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
      <% @shot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render 'form' %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<h1>Listing shots</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Push_url</th>
	<th>created_at</th>
	<th>updated_at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shots.each do |shot| %>
  <tr>
    <td><%= shot.content %></td>
    <td><%= shot.user_id %></td>
	<td><%= shot.push_url%></td>
	<td><%= shot.created_at%></td>
	<td><%= shot.updated_at%></td>
    <td><%= link_to 'Show', shot %></td>
    <td><%= link_to 'Edit', edit_shot_path(shot) %></td>
    <td><%= link_to 'Destroy', shot, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shot', new_shot_path %>

app/views/shots/new.html.erb
<h1>New shot</h1>

<%= render 'form' %>

<%= link_to 'Back', shots_path %>

app/views/shots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @shot.content %>
</p>

<p>
  <b>User:</b>
  <%= @shot.user_id %>
</p>


<%= link_to 'Edit', edit_shot_path(@shot) %> |
<%= link_to 'Back', shots_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Data</th>
	<th>created_at</th>
	<th>updated_at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.data %></td>
	<td><%= user.created_at%></td>
	<td><%= user.updated_at%></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Data:</b>
  <%= @user.data %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>